name: Deploy DotNet project to function app with a Linux environment

on:
  push:
    branches: # array of glob patterns matching against refs/heads. Optional; defaults to all
      - dev # triggers on pushes that contain changes in develop

env:
  AZURE_FUNCTIONAPP_NAME: function-app-adp-v2-dev  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './ImageResizeFunction'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '2.1.5'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}